apiVersion: apps/v1
kind: Deployment
metadata:
  name: datastore-frontend
  labels:
    type: frontend
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      type: frontend
  template:
    metadata:
      labels:
        type: frontend
    spec:
      containers:
        - name: datastore-frontend
          image: 816069171608.dkr.ecr.ap-south-1.amazonaws.com/datastore-frontend
          ports:
            - containerPort: 8080
          env:
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: datastore-fe-cm
                  key: API_URL
---
apiVersion: v1
kind: Service
metadata:
  name: datastore-frontend-svc
  namespace: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    type: frontend