serviceAccount:
  create: true

config:
  service: |
    [SERVICE]
        Flush        1
        Log_Level    info
        HTTP_Server  On
        HTTP_Listen  0.0.0.0
        HTTP_Port    2020

  inputs: |
    [INPUT]
        Name              tail
        Path              /var/log/containers/*.log
        Tag               kube.*
        Refresh_Interval  5
        Rotate_Wait       30
        Mem_Buf_Limit     10MB
        Skip_Long_Lines   On
        DB                /var/log/flb_kube.db
        DB.Sync           Normal

  outputs: |
    [OUTPUT]
        Name cloudwatch_logs
        Match *
        region ap-south-1
        log_group_name eks-app-logs
        log_stream_prefix fluent-bit-
        auto_create_group true