apiVersion: v1
kind: ConfigMap
metadata:
  name: datastore-be-cm
  namespace: backend
data:
  mysqlHost: jdbc:mysql://datastore-mysql-db.cp6iaig2gvk7.ap-south-1.rds.amazonaws.com/datastoredb
  mysqlUname: admin

  